[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/service"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/portfolio"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/gallery"
  to = "/index.html"
  status = 200
